# config.toml
[global]
basedir = "/cosma7/data/dp004/rttw52/manticore_data/production_runs/v2b/resimulations/2MPP_MULTIBIN_N256_DES_V2/R1024"
observer_coords = [500.0, 500.0, 500.0]
output_dir = "output"
boxsize = 1000.0

[mode1]
mcmc_start = 0
mcmc_end = 79
m200_mass_cut = 0.5e14
radius_cut = 400.0
eps = 1.75
min_samples = 9

[mode2]
target_snapshot = 10
min_cluster_size = 40

[mode3]
basedir = "/cosma7/data/dp004/rttw52/manticore_data/production_runs/v2b/resimulations/CONTROL_L1000/R1024"
mcmc_start = 0
mcmc_end = 9
m200_mass_cut = 0.5e14
radius_cut = 400.0
num_samplings = 8
eps = 3.75
min_samples = 5

[mode4]
basedir = "/cosma7/data/dp004/rttw52/manticore_data/production_runs/v2b/resimulations/CONTROL_L1000/R1024"
mcmc_start = 0
mcmc_end = 9
m200_mass_cut = 0.5e14
radius_cut = 400.0
target_snapshot = 10
observer_coords = [500.0, 500.0, 500.0]
